name = "irish-lotto-worker"
main = "src/index.js"
compatibility_date = "2024-01-22"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "irish-lotto"
database_id = "aaed0800-2419-491d-99db-b9b21239e798"

# Cron Trigger for automatic updates
[triggers]
crons = ["0 20 * * 3,6"] # Runs at 8 PM on Wednesday and Saturday (Irish Time)
